name: Run tests
run-name: ${{ github.workflow }} | "${{ github.event.head_commit.message }}"
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Upgrade pip
        run: /usr/bin/env python3.11 -m pip install --upgrade pip
      - name: Install dependencies
        run: /usr/bin/env python3.11 -m pip install -r requirements.txt
      - name: Run tests
        run: pytest
