name: Run tests
run-name: ${{ github.workflow }} | "${{ github.event.head_commit.message }}"
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run tests
        run: uv run pytest
